/* eslint-disable */
export default {
  getTweetsList: "/tag",
  getTweetsByTagSearch: "/search/quote?tag=",

  login: "/PHR/api/Doctor/Login",
  register: "/PHR/api/Person/RegistrationAndLogin",
  phoneExists: "/Security/api/Account/CheckIfPrimaryPhoneExists",
  generateOtp: "/Security/api/OTP/Generate",
  validateOtp: "/Security/api/OTP/Validate",
  resetPassword: "/Security/api/OTP/Generate",
  setNewPassword: "/Security/api/Security/ChangePassword",
  fetchSpecialization: "/CRM/api/DoctorLookup/ListSpecialization",
  fetchDegree: "/CRM/api/DoctorLookup/ListDegrees",
  fetchFellowships: "/CRM/api/DoctorLookup/ListFellowships",
  fetchEmpanelments: "/CRM/api/DoctorLookup/ListEmpanelments",
  fetchRegistrationCouncils: "/CRM/api/DoctorLookup/ListRegistrationCouncils",
  checkIfEmailExists: "/Security/api/Account/CheckIfEmailExists",
  checkIfMobileExists: "/Security/api/Account/CheckIfPrimaryPhoneExists",
  registerDoctor: "/PHR/api/Doctor/DoctorRegistration",
  registerDoctorOld: "/PHR/api/Doctor/DoctorRegistrationOld",
  saveSessions: "/CRM/api/DoctorProfile/SaveDoctorSession",
  getDoctorProfile: "/CRM/api/DoctorProfile/GetDoctor",
  addClinicDetails: "/CRM/api/Supplier/AddSupplier",
  addPatientDetails: "/PHR/api/Patient/PatientRegistration",
  getPatientHeaderSearch: "/CRM/api/Customer/ListLookup",
  getPatientHeaderSearchByDoctorID: "/CRM/api/Customer/ListLookupByDoctorID",
  getPatientList: "/CRM/api/Customer/List",
  getDrugList: "/PHR/api/DoctorLookup/ListMedicine",
  saveMedicineInStaging: "/PHR/api/Doctor/SaveMedicineInStaging",
  fetchStagingDrugs: "/PHR/api/Doctor/GetDrugsStaging",
  fetchDrugIndexList: "/PHR/api/Doctor/ListMedicines",
  fetchFilteredDrugIndexList: "/PHR/api/DoctorLookup/ListDoctorMedicines",
  getAppointmentList: "/CRM/api/Customer/ListAppointment",
  getDoctorScheduleDetails: "/CRM/api/DoctorProfile/GetDoctorScheduleDetails",
  bookAppointment: "/PHR/api/Patient/BookAppointment",
  getAppointmentCount: "/CRM/api/DoctorProfile/GetDoctorAppointmentCount",
  getAppointmentCountForDoctor:
    "/CRM/api/Receptionist/GetAppointmentCountByDates",
  //getPatientDetailByAppointmentId: '/CRM/api/Customer/GetCustomer',
  //getPatientDetailAfterStart: '/PHR/api/Patient/GetPatient',
  getPatientDetailByAppointmentId: "/PHR/api/Patient/GetPatient",
  removeStagingDrug: "/PHR/api/Doctor/RemoveDrugsStaging",
  saveRescheduleAppointment: "/CRM/api/Customer/RescheduleAppointment",
  saveDrugsToDoctorList: "/PHR/api/Doctor/SaveMedicines",
  fetchDrugTypesMaster: "/PHR/api/DoctorLookup/ListMedicineType",
  removeMedicineFromList: "/PHR/api/Doctor/RemoveMedicines",
  rescheduleAppointment: "/CRM/api/Customer/RescheduleAppointment",
  cancelAppointment: "/CRM/api/Customer/UpdateStatus",
  checkInAppointment: "/CRM/api/Customer/Checkin",
  updateDrugIndexMedicine: "/PHR/api/Doctor/UpdateMedicine",
  procedureLookup: "/PHR/api/DoctorLookup/ListProcedures",
  procedureLookupSMCT: "/PHR/api/DoctorLookup/ListProceduresSMCT",
  updateProcedureFrquency: "/PHR/api/Doctor/SaveDoctor_Procedures",
  saveProcedureToStaging: "/PHR/api/Doctor/SaveProcedureStaging",
  fetchProceduresFromStaging: "/PHR/api/Doctor/GetProcedureStaging",
  removeProcedureFromStaging: "/PHR/api/Doctor/RemoveProcedureStaging",
  saveProceduresToDoctorList: "/PHR/api/Doctor/SaveProcedures",
  fetchDoctorsProcedureList: "/PHR/api/Doctor/ListProcedures",
  removeProcedureFromDoctorsList: "/PHR/api/Doctor/RemoveProcedures",
  updateProcedureInDoctorList: "/PHR/api/Doctor/UpdateProcedure",
  investigationLookup: "/PHR/api/DoctorLookup/ListInvestigation",
  updateInvestigationFrequency: "/PHR/api/Doctor/SaveDoctor_Investigation",
  startConsultation: "/PHR/api/Patient/StartConsultation",
  symptomsLookUp: "/PHR/api/DoctorLookup/ListSymptoms",
  symptomsLookUpSMCT: "/PHR/api/DoctorLookup/ListSymptomsSMCT",
  updateSymptomsFrquency: "/PHR/api/Doctor/SaveDoctor_Symptoms",
  getDiseasesList: "/PHR/api/DoctorLookup/ListDiseases",
  getSMCTDiseasesList: "/PHR/api/DoctorLookup/ListDiseasesSMCT",
  updateDiseaseFrequency: "/PHR/api/Doctor/SaveDoctor_Diseases",
  getProcedureList: "/PHR/api/DoctorLookup/ListProcedures",
  fetchDiagnosisList: "/PHR/api/Patient/ListAllConsultation",
  fetchVitalList: "/PHR/api/Patient/ListConsultation",
  fetchQuickView: "/PHR/api/Patient/GetConsultation",
  fetchDoctorsOrderSetList: "/PHR/api/Doctor/ListOrderset",
  fetchDoctorsOrderSetDetails: "/PHR/api/Doctor/GetOrderset",

  saveOrderSetStaging: "/PHR/api/Doctor/SaveOrdersetStaging",
  saveOrderSet: "/PHR/api/Doctor/SaveOrderset",
  removeOrderSetStaging: "/PHR/api/Doctor/RemoveOrdersetStaging",
  removeOrderSet: "/PHR/api/Doctor/RemoveOrderset",
  getOrdersetStaging: "/PHR/api/Doctor/GetOrdersetStaging",

  savePrescription: "/PHR/api/Patient/SaveConsultation",
  fetchPatientPrescription: "/PHR/api/Patient/GetConsultation",
  stopConsultation: "/PHR/api/Patient/StopConsultation",
  generateOrderOnComplete: "/CRM/api/Order/GenerateOnBooking",
  generatePrescription: "/proxy/Prescription/DownloadPrescription",
  saveHelpQuery: "/CRM/api/DoctorProfile/SendQueryRequest",
  getOnboardRequestList: "/CRM/api/DoctorProfile/ListOnboardRequests",
  editPatient: "/PHR/api/Patient/EditPatient",
  setProfilePicture: "/CRM/api/DoctorProfile/SaveProfileImage",
  setClinicProfilePicture: "/CRM/api/Supplier/SaveClinicProfileImage",
  documentUploadOfDoctor: "/CRM/api/DoctorProfile/UploadDocuments",
  getByPhoneNumberOrEmailID: "/CRM/api/Customer/GetByPhoneNumberOrEmailID",
  approveRequest: "/CRM/api/DoctorProfile/ApproveRequest",
  rejectRequest: "/CRM/api/DoctorProfile/RejectRequest",
  holdRequest: "/CRM/api/DoctorProfile/HoldRequest",
  updateStatus: "/CRM/api/DoctorProfile/UpdateStatus",
  getRequestDetails: "/CRM/api/DoctorProfile/GetRequestDetails",
  updateDoctorBasicDetails: "/CRM/api/DoctorProfile/UpdateDoctor",
  updateDoctorClinicDetails: "/CRM/api/Supplier/UpdateSupplier",
  // Receptionist API URLS
  getAppointmentCountForReceptionist:
    "/CRM/api/Receptionist/GetAppointmentCount",
  getAppointmentListForReceptionist: "/CRM/api/Receptionist/ListAppointment",
  // fetchReceptionistDoctorMapping: '/CRM/api/Receptionist/GetByAccountID',
  listProceduresWithPricing: "/PHR/api/Doctor/ListProceduresWithPricing",
  saveProcedurePricing: "/CRM/api/Receptionist/SaveProcedurePricing",
  removeDoctorProcedurePricing:
    "/CRM/api/Receptionist/RemoveDoctorProcedurePricing",
  listConsultationPricingDetails: "/CRM/api/Receptionist/ListPricingDetails",
  saveConsultationDoctorPricing: "/CRM/api/Receptionist/SaveDoctorPricing",
  removeDoctorConsultationPricing: "/CRM/api/Receptionist/RemoveDoctorPricing",
  saveDoctorPrintSetting: "/CRM/api/DoctorProfile/SaveDoctorPrintSetting",
  listPricingLookupForProcedureAndConsulatation:
    "/CRM/api/Receptionist/ListPricingLookup",
  calendarGetAppointmentListByDate: "/CRM/api/Calendar/GetByDay",
  generateInvoice: "/CRM/api/Order/Save",
  getInvoiceDetails: "/CRM/api/Order/Get",
  getInvoiceList: "/CRM/api/Order/List",
  getPatientInvoiceList: "/CRM/api/Order/InvoiceList",
  generatePrintInvoice: "/proxy/Invoice/DownloadInvoice",
  GetDoctorProfileSetting: "/PHR/api/Doctor/GetDoctorProfileSetting",
  ListofVitals: "/PHR/api/Doctor/ListProfileMaster",
  SaveDoctorProfileSetting: "/PHR/api/Doctor/SaveDoctorProfileSetting",
  invoiceSendMail: "/CRM/api/Order/SendMail",
  getReportByTotalCollection: "/CRM/api/Report/GetOverallReport",
  getReportByModeOfPayment: "/CRM/api/Report/GetPaymentReport",
  getReportByModeOfPatientPayment: "/CRM/api/Report/GetPatientReport",
  getReportByProduct: "/CRM/api/Report/GetProductReport",
  calendarGetAppointmentListByView: "/CRM/api/Calendar/GetByGroupCode",
  getEmedMasterList: "/PHR/api/DoctorLookup/ListEMEDMedicines",
  getEmedDoctorSuggestionList: "/PHR/api/DoctorLookup/ListDoctorLocalMedicines",
  getEmedDosageList: "/PHR/api/DoctorLookup/ListDoses",
  getEmedFrequencyList: "/PHR/api/DoctorLookup/ListFrequency",
  getEmedDurationsList: "/PHR/api/DoctorLookup/ListDuration",
  getDoctorFreeTextMedicinesList:
    "/PHR/api/DoctorLookup/ListDoctorFreeTextMedicines",
  saveMedicalNote: "/PHR/api/Patient/SaveNote",
  getMedicalNote: "/PHR/api/Patient/GetNote",
  getMedicalNoteList: "/PHR/api/Patient/ListNote",
  getDocumentType: "/PHR/api/DoctorLookup/ListDocumentType",
  getEpisodeType: "/PHR/api/Patient/GetAllConsultationEpisode",
  uploadPatientAttachment: "/PHR/api/Document/SaveDocuments",
  getYearMonthWithPatientCountReport: "/PHR/api/Patient/GetPatientCountReport",
  // getUpcomingAppointment: '/CRM/api/Customer/GetLatestAppointment',
  getUpcomingAppointment: "/CRM/api/Customer/GetAllAppointments",
  getLatestConsultation: "/PHR/api/Patient/GetLatestConsultation",
  getImmunisation: "/PHR/api/Patient/GetImmunisation",
  getParameterReport: "/PHR/api/PatientReport/GetParameterReport",
  sendPrescriptionMail: "/PHR/api/Patient/SendEmail",
  DeleteDocument: "/PHR/api/Document/DeleteDocument",
  savePrescriptionSettings: "/PHR/api/Doctor/SavePrescriptionSettings",
  getPrescriptionSettings: "/PHR/api/Doctor/GetPrescriptionSettings",
  SaveImmunisation: "/PHR/api/Patient/SaveImmunisation",
  GetMedicalBackground: "/PHR/api/Patient/GetMedicalBackground",
  SaveAllergy: "/PHR/api/Patient/SaveAllergy",
  SaveFamilyHistory: "/PHR/api/Patient/SaveFamilyHistory",
  SavePastIllness: "/PHR/api/Patient/SavePastIllness",
  SavePatientLifestyle: "/PHR/api/Patient/SavePatientLifestyle",
  ListMedication: "/PHR/api/Patient/ListMedication",
  SaveMedication: "/PHR/api/Patient/SaveMedication",
  UpdateMedicationStatus: "/PHR/api/Patient/UpdateMedicationStatus",
  DeleteMedication: "/PHR/api/Patient/DeleteMedication",
  ListAttachment: "/PHR/api/Document/ListConsultationDocument",
  SaveMedicalSection: "/PHR/api/Patient/SaveMedicalSection",
  GetMedicalSection: "/PHR/api/Patient/GetMedicalSection",
  DeleteMedicalSection: "/PHR/api/Patient/DeleteMedicalSection",
  searchPatientGlobalIndex: "/PHR/api/PatientLookup/SearchPatientGlobalIndex",
  markAsCompleted: "/PHR/api/Patient/MarkAppointmentComplete",
  GetSessionData: "/CRM/api/DoctorProfile/GetSessionData",
  StartConsultationWithAppointment:
    "/PHR/api/Patient/StartConsultationWithAppointment",
  // SaveErrorLog: "/Security/api/Account/SaveErrorLog",
  ListFrequentSymptoms: "/PHR/api/DoctorLookup/ListFrequentSymptoms",
  ListSymptomsSMCT: "/PHR/api/DoctorLookup/ListSymptomsSMCT",
  RemoveSymptoms: "/PHR/api/Doctor/RemoveSymptoms",
  ListDiseasesSMCT: "/PHR/api/DoctorLookup/ListDiseasesSMCT",
  ListDiseases: "/PHR/api/DoctorLookup/ListDiseases",
  ListFrequentDiseases: "/PHR/api/DoctorLookup/ListFrequentDiseases",
  RemoveDiagnoDiseases: "/PHR/api/Doctor/RemoveDiseases",
  SaveDoctorSymptom: "/PHR/api/Doctor/SaveDoctor_Symptoms",
  SaveChiefComplaint: "/PHR/api/Patient/SaveChiefComplaint",
  SaveDoctorDiagnosis: "/PHR/api/Doctor/SaveDoctor_Diseases",
  ListActiveConsultation: "/PHR/api/Patient/ListActiveConsultation",
  // ListUpcomingAppointments: "/CRM/api/Customer/GetAllAppointments",
  DeleteAppointmentwithConsultation:
    "/PHR/api/Patient/DeleteAppointmentwithConsultation",
  SaveDoctorEMRAnchorSetting: "/PHR/api/Doctor/SaveDoctorEMRAnchorSetting",
  GetDoctorEMRAnchorSetting: "/PHR/api/Doctor/GetDoctorEMRAnchorSetting",
  saveExaminationWithoutAppointment:
    "/PHR/api/Patient/SaveExaminationWithoutAppointment",
  getLatestExamintation: "/PHR/api/Patient/GetLatestExamintation",
  listRecentPatient: "/CRM/api/Customer/ListRecentPatient",
  ListConsultationMedication: "/PHR/api/Patient/ListConsultationMedication",
  SaveConsultationMedicine: "/PHR/api/Patient/SaveConsultationMedicine",
  RemoveConsultation: "/PHR/api/Patient/RemoveConsultation_Medicines",
  getEmedListInstruction: "/PHR/api/DoctorLookup/ListInstruction",
  RemoveConsultationMedicines: "/PHR/api/Patient/RemoveConsultation_Medicines",
  // Notifications API url
  GetNotificationsCount: "/CRM/api/DoctorNotification/GetCount",
  RemoveAllNotification: "/CRM/api/DoctorNotification/RemoveAll",
  ListNotification: "/CRM/api/DoctorNotification/List",
  ListMedicalBackgrounds: "/PHR/api/DoctorLookup/ListMedicalBackground",
  ListFrequentProcedures: "/PHR/api/DoctorLookup/ListFrequentProcedures",
  SavePersonalHistory: "/PHR/api/Patient/SavePastIllness",
  SaveFamilyHistory: "/PHR/api/Patient/SaveFamilyHistory",
  SaveAllergy: "/PHR/api/Patient/SaveAllergy",
  SavePatientLifestyle: "/PHR/api/Patient/SavePatientLifestyle",
  SaveImmunisation: "/PHR/api/Patient/SaveImmunisation",
  SaveSurgery: "/PHR/api/Patient/SaveSurgery",
  RemoveProcedure: "/PHR/api/Doctor/RemoveProcedure",
  getEmedDefaultDoses: "/PHR/api/DoctorLookup/GetDefaultDoses",
  ListFrequentMedicineSuggestions:
    "/PHR/api/DoctorLookup/ListFrequentMedicineSuggestions",
};
